surf_threshold: 100
bof_groups: 100
frames_to_jump: 1
bof_vocabulary_path: '/home/ballester/catkin_ws/src/dolphin_slam/bow_vocabularies/'
image_topic: '/image'
bag_file: '/home/ballester/datasets/girona/girona.bag'
