surf_threshold: 500
bof_groups: 1000
frames_to_jump: 10
bof_vocabulary_path: '/home/lsilveira/Codigos/indigo_ws/src/dolphin_slam/bof_vocabularies/'
image_topic: '/image'
#bag_file: '/home/ballester/datasets/girona/girona.bag'
