number_of_neurons: [20, 20, 20]
distance_between_neurons: [ 0.25, 0.25, 0.25]
excitatory_variance: [0.1, 0.1, 0.1]
input_learning_rate: 0.25     
multiple_local_view_active: true                                
use_gaussian_weights: false
